name: Intentional Form
favicon: null
layout_spectrum: 0.927487570559606
typography_spectrum: 0.3891367625910789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2625472992658615
  lightness: 0.7523917062208056
  saturation: 0.4903246962931007
  rhythmicContrast: 0.5083600257057697
purpose: []
