name: Intentional Form
favicon: null
layout_spectrum: 0.25055
typography_spectrum: 1
title: Intentional Form
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#053bdc'
    - '#4066f7'
    - '#6f89fe'
    - '#a8b3fd'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
